shas {
  correctPin = "1234"
  exitDelay = 5 seconds
  entryDelay = 5 seconds
}

pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"

  actor {
    provider = "cluster"

    serialization-bindings {
      "pcd.shas.common.MySerializable" = jackson-json
    }
  }

  remote {
    artery {
      canonical {
        hostname = "127.0.0.1"
        port = 0
      }
    }
  }

  cluster {
    seed-nodes = [
      "pekko://shas-cluster@127.0.0.1:2551",
      "pekko://shas-cluster@127.0.0.1:2552"
    ]
    seed-node-timeout = 1s
    retry-unsuccessful-join-after = 1s
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }
}
