package pcd.poool.model.physics.config;

import java.util.ArrayList;
import java.util.List;
import pcd.poool.model.common.math.P2d;
import pcd.poool.model.common.math.V2d;
import pcd.poool.model.physics.common.Ball;
import pcd.poool.model.physics.common.BoardConf;
import pcd.poool.model.physics.common.Boundary;

/**
 * Playable high-load board configuration with one thousand small balls.
 *
 * <p>The layout is intended for manual testing of the platform-threaded
 * version: it is heavier than the standard playable board, but less extreme
 * than the massive benchmark configuration.
 */
public class ThousandBallsBoardConf implements BoardConf {

    /** Number of small balls generated by this configuration. */
    public static final int SMALL_BALL_COUNT = 1_000;

    private static final Boundary BOARD_BOUNDARY = new Boundary(-1.5, -1.0, 1.5, 1.0);
    private static final double CUE_RADIUS = 0.05;
    private static final P2d HUMAN_START = new P2d(0, -0.78);
    private static final P2d BOT_START = new P2d(0, 0.78);
    private static final double SMALL_BALL_RADIUS = 0.008;
    private static final int GRID_ROWS = 25;
    private static final int GRID_COLUMNS = 40;
    private static final double GRID_START_X = -0.78;
    private static final double GRID_START_Y = -0.35;
    private static final double GRID_SPACING = 0.04;
    private static final V2d RESTING = new V2d(0, 0);

    /**
     * Creates the one-thousand-ball board configuration.
     */
    public ThousandBallsBoardConf() {
    }

    @Override
    public Boundary getBoardBoundary() {
        return BOARD_BOUNDARY;
    }

    @Override
    public Ball getPlayerBall() {
        return Ball.ofUniformMaterial(HUMAN_START, CUE_RADIUS, RESTING);
    }

    @Override
    public Ball getBotBall() {
        return Ball.ofUniformMaterial(BOT_START, CUE_RADIUS, RESTING);
    }

    @Override
    public List<Ball> getSmallBalls() {
        var balls = new ArrayList<Ball>(SMALL_BALL_COUNT);
        for (int row = 0; row < GRID_ROWS; row++) {
            for (int col = 0; col < GRID_COLUMNS; col++) {
                double x = GRID_START_X + col * GRID_SPACING;
                double y = GRID_START_Y + row * GRID_SPACING;
                balls.add(Ball.ofUniformMaterial(new P2d(x, y), SMALL_BALL_RADIUS, RESTING));
            }
        }
        return balls;
    }
}
